KEYCODE.SFT = {
  'KC_1' : '!',
  'KC_2' : '@',
  'KC_3' : '#',
  'KC_4' : '$',
  'KC_5' : '%',
  'KC_6' : '^',
  'KC_7' : '&',
  'KC_8' : '*',
  'KC_9' : '(',
  'KC_0' : ')',

  'KC_A' : 'A',
  'KC_B' : 'B',
  'KC_C' : 'C',
  'KC_D' : 'D',
  'KC_E' : 'E',
  'KC_F' : 'F',
  'KC_G' : 'G',
  'KC_H' : 'H',
  'KC_I' : 'I',
  'KC_J' : 'J',
  'KC_K' : 'K',
  'KC_L' : 'L',
  'KC_M' : 'M',
  'KC_N' : 'N',
  'KC_O' : 'O',
  'KC_P' : 'P',
  'KC_Q' : 'Q',
  'KC_R' : 'R',
  'KC_S' : 'S',
  'KC_T' : 'T',
  'KC_U' : 'U',
  'KC_V' : 'V',
  'KC_W' : 'W',
  'KC_X' : 'X',
  'KC_Y' : 'Y',
  'KC_Z' : 'Z',

  'KC_EQL' : '+',
  'KC_GRV' : '~',
  'KC_QUOT' : '"',
  'KC_COMM' : '<',
  'KC_DOT' : '>',
  'KC_LBRC' : '{',
  'KC_RBRC' : '}',
  'KC_BSLS' : '|',
  'KC_SLSH' : '?',
  'KC_SCLN' : ':',

  'KC_MINS' : '_',
};

KEYCODE.LSFT = KEYCODE.SFT;
KEYCODE.RSFT = KEYCODE.SFT;
